---
namespace: community
name: wordpress
version: 1.0.1
readme: README.md
authors:
  - Yamen Othmani
description: MYSQL
license_file: COPYING
tags:
  - v1
repository: https://github.com/hanniDEV/wordpress_role.git
documentation: https://github.com/hanniDEV/wordpress_role.git
homepage: https://github.com/hanniDEV/wordpress_role.git
issues: https://github.com/hanniDEV/wordpress_role.git
build_ignore: https://github.com/hanniDEV/wordpress_role.git
  - .gitignore