
---
#       WORDPRESS MYQL

- name: Create MYSQL directory 
  ansible.builtin.file:
    path: /home/ubuntu/MYSQL
    state: directory
    mode: '0755'


- name: Create WORDPRESS directory 
  ansible.builtin.file:
    path: /home/ubuntu/WORDPRESS
    state: directory
    mode: '0755'

- name: Create a network
  docker_network:
    name: "{{ my_network }}"

- name: start MYSQL containers
  docker_container:
    name: "{{ mysql_container_name }}"
    image: "{{ mysql_container_name }}"
    state: started
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    ports:
      - "{{ mysql_exposed_port }}:3306"
    volumes:
      - "{{ mysq_volume }}:/var/lib/mysql"

- name: create WORDPRESS containers
  docker_container:
    name: "{{ wordpress_container_name }}"
    image: "{{ wordpress_container_name }}"
    state: started
    env:
      WORDPRESS_DB_HOST: mysql_host
      WORDPRESS_DB_USER: "{{ mysql_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql_password }}"
      WORDPRESS_DB_NAME: "{{ mysql_database }}"
    ports:
      - "{{ wordpress_exposed_port }}:80"        
    links:
      - "{{ mysql_container_name }}:mysql_host"
    volumes:
      - "{{ wordpress_volume }}:/var/www/html"

- name: Add a container to a network, leaving existing containers connected
  docker_network:
    name: "{{ my_network }}"
    connected:
      - "{{ mysql_container_name }}"
      - "{{ wordpress_container_name }}"
    appends: yes
